[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
 # relatedtext = "Related"
  favicon = "/favicon.png"
  #list items
  datesinlist = true
  authorsinlist = true
sectionPagesMenu = "main"
  #footer items
  nextprev = true
  taglist = true
  showrss = true

## when everything below is commented out, the site compiles but no navbar

[languages]

  [languages.en]
    disabled = false
    languageName = 'English'
    weight = 1
     # [languages.en.params]
         # translations = "Tłumaczenia"
  [[languages.en.menus.main]]
    name = 'Home'
    weight = 10
    pageref = '/'

  [[languages.en.menus.main]]
    name = 'Blog'
    weight = 20
    pageref = '/blog'


  [[languages.en.menus.main]]
    name = 'Contact'
    weight = 50
    pageref = '/contact'

  [languages.pl]
    disabled = false
    languageName = 'Polski'
    weight = 2
    contentDir = 'content/pl'
         
  [[languages.pl.menus.main]]
    name = 'Home'
    weight = 10
    pageref = '/'

  [[languages.pl.menus.main]]
    name = 'Blog'
    weight = 20
    pageref = '/blog'

  [[languages.pl.menus.main]]
    name = 'Kontakt'
    weight = 50
    pageref = '/contact'

# sectionPagesMenu = 'main'
[menus]
  [[menus.main]]
    name = 'Home'
    weight = 10
    pageref = '/'

  [[menus.main]]
    name = 'Blog'
    weight = 20
    pageref = '/blog'

  [[menus.main]]
    name = 'Contact'
    weight = 50
    pageref = '/contact'

